name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Install modules
        uses: npm install

      - name: Build production project
        uses: npm run build:prod

      - name: Linting Typescript
        uses: npm run lint:ts

      - name: Linting SCSS
        uses: npm run lint:scss

      - name: Unit testing
        uses: npm run test:unit
